package(
  default_visibility = ["//src:__subpackages__"],
)

android_library(
  name = "main_activity", 
  srcs = [
    "MainActivity.kt",
  ],
  manifest = "AndroidManifest.xml",
  resource_files = glob(["res/**"]),
)